### ISSUE TITLE
usage of hmmearch

### ISSUE THREAD

**Issue by jianshu93** [mustafa-guler/libhmmer-sys#3]
Hello Mustafa-guler,

Thanks for making this binding, so for usage all we need is to just call the hmmsearch function right. A little bit confused for how to use it in rust.

Thanks,

Jianshu
Jianshu

**Comment by mustafa-guler** [comment]
Hi Jianshu,

There is no such function in this library. These are very thin wrappers around the public interface of libhmmer and libeasel from the hmmer repository. They provide only the building blocks for implementing the final HMMER binaries like hmmsearch but no actual final entrypoint. The idea is these could be used to rebuild the final binaries from HMMER as a rust library without redoing all the hard work of the HMMER team. However, unfortunately I haven't had time to do that.

There are few options if you'd like to execute HMMER from a rust crate:
1. Run it as a subcommand (without this library)
2. Use the functions exposed in this library to rebuild the HMMER methods you're interested in (most likely by referencing relevant *.c files) inside of rust. For hmmsearch you could replicate (roughly) `hmmer/src/hmmsearch.c` from the submodule in this repo.

**Comment by wwood** [comment]
Hi both,

You can now run hmmsearch from Rust using hmmer-rs without going unsafe (at least on the surface). i.e. I implemented option (2) above.

I pushed the first version of hmmer-rs to https://crates.io/crates/hmmer-rs - hopefully that will be useful here and as a starting point for exposing more of the HMMER API.

ben

**Comment by jianshu93** [comment]
Hello ben，

Many thanks for making this！This is extremely useful. We now have both rust hmmer and python hmmer bindings！

Jianshu

**Comment by jianshu93** [comment]
Hello Mustafa-guler,

I found that hmmer does compile on ARM64/aarh64 platforms if using the develop branch, which is here: https://github.com/EddyRivasLab/hmmer/tree/h3-arm

and the easel is here: https://github.com/EddyRivasLab/easel/tree/develop

Since both are not released yet. I am wondering whether you could update to use this new branch so that we can use it on any platforms. 


Thanks,

Jianshu

**Comment by jianshu93** [comment]
Hello Ben, 


Since Mustafa-guler is not active any more (according to our previous communication), I think we can do it by updating the libhmmer-sys to allow compiling on ARM64/aarch64, I imagine it is very easy, just replace the @hmmer folder to the h3-arm branch (also easel) because all function are exactly the same except sse2neon was used when detecting an arm64/aarch64 platform info.

Thanks,

Jianshu

**Comment by mustafa-guler** [comment]
@jianshu93

I don't want to update this library to use non main-branched parts of HMMER. If your ARM requirements are because of one of the newer Macs you can use a x86-64 rust target via rustup and Rosetta will handle all the SIMD calls in HMMER.
