### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by wwood** [mustafa-guler/libhmmer-sys#5]
Hi,

This library seems like exactly what I'm looking for - thanks very much for setting it up.

I had a crack at using it, but found some small holes e.g. `easel/easel.h:#define eslERRBUFSIZE 128` is not included in the library. Would it be straightforward to include the easel headers too?

I also had a crack at making a more idiomatic Rust interface building upon your good work here, though I have not had time to get very far just yet (and may or may not continue work on it, depending on how the science goes). https://github.com/wwood/hmmer-rs - I wonder if there are other similar code or examples that might be useful? Contributions there most welcome.

Thanks,
ben

**Comment by wwood** [comment]
Hi again, 

Just FYI I pushed the first version of hmmer-rs to https://crates.io/crates/hmmer-rs/0.1.0 - hopefully that will be useful.

For any missing #defines I created a new file and defined them there in hmmer-rs. I would imagine in future that there'd be a more standardised approach, but I just wanted to push something out.

Thanks again for writing these raw bindings.
ben

**Comment by mustafa-guler** [comment]
Sorry for the delay.

We do actually have something along the lines of what you've written that we use internally. However, ours is somewhat poorly tested and very tightly coupled to some functionality specific to our own HMMER use case. I don't want to release the version we have as is and am not sure I can dedicate time to getting it release ready in the near future.

Concerning missing easel macros, I've just released version 0.3.0 that includes the missing macro you mentioned (among many others from easel).

**Comment by wwood** [comment]
Thanks for the update - simplified things on my end. 

I know it isn't always easy/possible, but it would be great if further work of yours along these lines could be done more publicly so we (and whoever else out there) can build upon each others' work. Thanks again for writing this -sys library.
