### ISSUE TITLE
i32 constants

### ISSUE THREAD

**Issue by wwood** [mustafa-guler/libhmmer-sys#6]
Hi,

Updating 0.2 to 0.3 I noticed a lot of the constants don't have the right type when e.g. `libhmmer_sys::eslEOF` is u32, when code accepting that (e.g. the return status of `libhmmer_sys::p7_hmmfile_Read`) is i32.

Is there some reason to make them u32? It isn't particularly ergonomic to scatter `as i32` everywhere, though this isn't the worst thing in the world of course.

Thanks, ben

**Comment by mustafa-guler** [comment]
these are automatically generated via bindgen, it looks like it picks unsigned types for `#define`d constants by default.

**Comment by wwood** [comment]
Ah, right. Sorry, my knowledge of bindgen isn't very complete. What do you think about using something like

```
builder = builder.default_macro_constant_type(
    bindgen::MacroTypeVariation::Signed
)
```
to make it default to i32?
